implement altimeter audit log output for backup and restore
project-tsurugi/tateyama pull request #185
Opened 2024-02-07 13:05 UTC by ban-nobuhiro

backup, restore に対する audit_log の実装を追加しました。

案件: https://github.com/project-tsurugi/tsurugi-issues/issues/622

注意点
* `command` に埋める値は仮のものです
* `dbname`, `application_name`, `remote_host` については tateyama の既存コードを参考にし、同様の値を使用するようにしています
    * tgctl からの接続に対して `application_name:2011563` などという値が埋まります
 * backup はサーバ側では常に成功するため、常に `result:1` となります

2024-02-07 14:00 UTC, ashigeru requested changes
`command` 文字列だけ直していただいて、あとは問題なさそうです。

2024-02-08 00:27 UTC, t-horikawa approved these changes

2024-02-08 05:12 UTC, ban-nobuhiro commented on src/tateyama/datastore/service/core.cpp
> +            service::backup(req, "classic", backup_restore_success);
そのようにしました

2024-02-08 05:12 UTC, ban-nobuhiro commented on src/tateyama/datastore/service/core.cpp
> +            service::backup(req, "prusik", backup_restore_success);
そのようにしました

2024-02-08 05:14 UTC, ban-nobuhiro commented on src/tateyama/datastore/service/core.cpp
> +                    rb.source_case() == ns::RestoreBegin::kBackupDirectory ? "classic" : "prusik",
そのようにしました。(たぶん)

2024-02-08 05:15 UTC, ban-nobuhiro commented
`command` の値を変更しました。

2024-02-08 06:02 UTC, ashigeru approved these changes
LGTM

2024-02-08 07:08 UTC, merged

2024-02-08 07:09 UTC, ban-nobuhiro commented
merged, thanks